apiVersion: v1
kind: Service
metadata:
  name:  restate-agent-a2a
  namespace: {{ .Release.Namespace }}
  labels:
    app: restate-agent-a2a
spec:
  selector:
    app: restate-agent-a2a
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.containerPort }}