apiVersion: apps/v1
kind: Deployment
metadata:
  name: restate-agent-one
  namespace: {{ .Release.Namespace }}
  labels:
    app: restate-agent-one
spec:
  selector:
    matchLabels:
      app: restate-agent-one
      tier: restate-agent-one
  replicas: 1
  template:
    metadata:
      labels:
        app: restate-agent-one
        tier: restate-agent-one
    spec:
      containers:
      - name: restate-agent-one
        image: {{ .Values.global.imageRegistry }}/{{ .Values.deployment.image }}
        imagePullPolicy: Always 
        resources:
          limits:
            cpu: {{ .Values.deployment.resources.cpuLimit }}
            memory: {{ .Values.deployment.resources.memoryLimit }}
          requests:
            cpu: {{ .Values.deployment.resources.cpuRequest }}
            memory: {{ .Values.deployment.resources.memoryRequest }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        - name: PUBLIC_URL
          value: {{ .Values.ui.publicURL }}
        - name: LLM_API_BASE
          value: {{ .Values.llm.LLM_API_BASE }}
        - name: LLM_API_KEY
          value: {{ .Values.llm.LLM_API_KEY }}
        - name: LLM_MODEL_NAME
          value: {{ .Values.llm.LLM_MODEL_NAME }}
        - name: AZURE_INFERENCE_ENDPOINT
          value: {{ .Values.ui.azureInferenceEndpoint }}
        - name: AZURE_INFERENCE_CREDENTIAL
          value: {{ .Values.ui.azureInferenceCredential }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.ui.awsAccessKeyId }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.ui.awsSecretAccessKey }}
        - name: AWS_MODEL_ID
          value: {{ .Values.agent.model_id }}
        - name: AWS_REGION
          value: {{ .Values.agent.region }}
        - name: MCP_SERVER_URL
          value: {{ .Values.mcp.url }}
        - name: MCP_SERVER_TRANSPORT
          value: {{ .Values.mcp.transport }}
        - name: LANGSMITH_ENDPOINT
          value: {{ .Values.ui.langsmithEndpoint }}
        - name: LANGSMITH_API_KEY
          value: {{ .Values.ui.langsmithApiKey }}
        - name: LANGSMITH_PROJECT
          value: {{ .Values.ui.langsmithProject }}
  
